apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt5-config-pvc
  namespace: datapipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
