apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt5-log-pvc
  namespace: datapipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path
  volumeMode: Filesystem
